name: run-tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest]
                php: [8.2, 8.1, 8.0, 7.4, 7.3]
                dependency-version: [prefer-lowest, prefer-stable]
